# Generated by Django 5.2.1 on 2025-06-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officeorganization', '0006_alter_company_economic_code_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('is_incoming', models.BooleanField(default=False, verbose_name='نامه وارد')),
                ('is_outgoing', models.BooleanField(default=False, verbose_name='نامه صادره')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی نامه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای نامه',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دفتر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='officeorganization.department', verbose_name='واحد سازمانی')),
            ],
            options={
                'verbose_name': 'دفتر',
                'verbose_name_plural': 'دفاتر',
            },
        ),
        migrations.CreateModel(
            name='Secretariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دبیرخانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretariats', to='officeorganization.department', verbose_name='واحد سازمانی')),
                ('members', models.ManyToManyField(related_name='secretariats', to=settings.AUTH_USER_MODEL, verbose_name='اعضای دبیرخانه')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretariats', to='mailmanagements.office', verbose_name='دفتر')),
            ],
            options={
                'verbose_name': 'دبیرخانه',
                'verbose_name_plural': 'دبیرخانه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4')], default='A4', max_length=2, verbose_name='اندازه سربرگ')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('mail_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='شماره نامه')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='mail_signatures/', verbose_name='عکس امضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_draft', models.BooleanField(default=False, verbose_name='پیش\u200cنویس')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officeorganization.company', verbose_name='شرکت')),
                ('recipients', models.ManyToManyField(related_name='received_mails', to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mails', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailmanagements.mailcategory', verbose_name='دسته\u200cبندی')),
                ('secretariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mailmanagements.secretariat', verbose_name='دبیرخانه')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه\u200cها',
            },
        ),
    ]
