# Generated by Django 5.2.1 on 2025-06-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmanagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='تایید امضا'),
        ),
    ]
