# Generated by Django 5.2.1 on 2025-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmanagements', '0002_mail_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_confidential',
            field=models.BooleanField(default=False, verbose_name='محرمانه'),
        ),
        migrations.AddField(
            model_name='mail',
            name='notify_by_email',
            field=models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی از طریق ایمیل'),
        ),
        migrations.AddField(
            model_name='mail',
            name='notify_by_sms',
            field=models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی از طریق پیامک'),
        ),
    ]
