# Generated by Django 5.2.1 on 2025-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmanagements', '0003_mail_is_confidential_mail_notify_by_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
    ]
