/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { H1,Paragraph,Inputs,Button } from "@/components";
import { useState } from "react";
import {  toast } from 'react-toastify';

const ContactUs = () => {
    const [name,setName] =useState("")
    const [surname,setSurname] = useState("")
    const [email,setEmail] = useState("")
    const [content,setContent] = useState("")    

    const onChangeName = (e) =>{
        setName(e.target.value)
    }

    const onChangeSurname = (e) =>{
        setSurname(e.target.value)
    }

    const onChangeEmail= (e) =>{
        setEmail(e.target.value)
    }

    const onChangeContent = (e) =>{
        setContent(e.target.value)
    }


    const mainDivContact = css`
        width:100%;
        height:100vh;
        background-color:rgb(8, 0, 83);
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        color:white;
        position:relative;
        overflow:hidden;
    `
    const headerDivContact = css`
        width:100%;
        height:fit-content;
        display:flex;
        align-items:center;
        justify-content:center;
        background-image:linear-gradient(to bottom right, rgba(0, 6, 61, 0.95) , rgba(0, 6, 61, 0.7)) ,url(./images/contact/contactus.jpg);
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;
        padding:4rem 0;
        position:absolute;
        top:5%;
        animation: topToDown 1s ease-in;
    `
    const sectionMaps = css`
        width:60%;
        height:56%;
        position:absolute;
        top:29%;
        left:3%;
        border-radius:10px;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        direction:rtl;
        overflow-y:auto;
        overflow-x:none;
        ::-webkit-scrollbar {
          display: none;
        }
        animation:dropDownAnim 1s ease-in;
    `

    const sectionInfoSubmit = css`
        width:30%;
        height:23%;
        position:absolute;
        top:29%;
        left:67%;
        border-radius:10px;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        direction:rtl;
        padding:1rem 0;
        ::-webkit-scrollbar {
          display: none;
        }
          animation:dropDownAnim 2s ease-in;
    `
    const notify = (message) => toast(<Paragraph>{message}</Paragraph>);
    const submitBehaviour = (e) =>{
        if (e){
            e.preventDefault()
        }
        const data = {
            "name":name,
            "surname":surname,
            "email":email,
            "content":content,
        }
        if(name === "" || surname === "" || email === "" || content === ""){
            notify("لطفا فرم را پر کنید")
        }else{
            notify("نظر شما ازسال شد")
        }
        
        console.log("USER",data)
    }

    return(
        <>
        <Head>
          <title>سرزمین من | ارتباط با ما</title>
          <meta name="description" content="Generated by Ali Mahmoodi" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.ico" />
        </Head>
        <div css={mainDivContact}>
            <div css={headerDivContact}>
                <H1>ارتباط با ما</H1>
            </div>
            <iframe css={sectionMaps} src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d36632.66488095278!2d51.33522048691619!3d35.75324491120463!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8e00491ff3dcd9%3A0xf0b3697c567024bc!2sTehran%2C%20Tehran%20Province%2C%20Iran!5e0!3m2!1sen!2ssg!4v1742036492315!5m2!1sen!2ssg"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
            </iframe>
            <form onSubmit={submitBehaviour} css={sectionInfoSubmit}>
                <div css={css`margin-bottom:2rem;width: 100%;`}>
                    <Inputs inputDef={onChangeName} name={"name"} label={"نام"} type={"text"} value={name}/>
                </div>
                <div css={css`margin-bottom:2rem; width: 100%;`}>
                <Inputs inputDef={onChangeSurname} name={"surname"} label={" نام خانوادگی"} type={"text"} value={surname}/>           
                </div>
                <div css={css`margin-bottom:2rem; width: 100%;`}>
                <Inputs inputDef={onChangeEmail} name={"email"} label={"ایمیل"} type={"email"} value={email}/>
                </div>
                <div css={css`margin-bottom:2rem; width: 100%;`}>
                    <Inputs inputDef={onChangeContent} type={"textarea"} label={"شرح درخواست"} name={"content"} value={content}/>
                </div>
                
                <div css={css`margin-bottom:2rem; width: 100%;`}>
                    <Button type={"submit"}>ارسال</Button>          
                </div>                                           
            </form>
        </div>

        </>
        
    )
}

export default ContactUs