# Dockerfile for Django (Development Environment)

# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set environment variables for locale (استفاده از لوکیل پیش‌فرض)
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

# Set the working directory in the container
WORKDIR /usr/src/app

# Install system dependencies (فقط پکیج‌های ضروری)
RUN apt-get update && \
    apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY ./core_backend/ /usr/src/app
COPY ./envs/dev/django/.env /usr/src/app

# Install netcat-openbsd for checking database readiness
RUN apt-get update && \
    apt-get install -y netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

# Expose port 8000
EXPOSE 8000

# Wait for database to be ready
COPY ./dockerfiles/dev/django/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]