# Dockerfile for Django (Development Environment)

# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Set environment variables for locale (استفاده از لوکیل پیش‌فرض)
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

# Set the working directory in the container
WORKDIR /usr/src/app

# Install system dependencies (فقط پکیج‌های ضروری)
RUN apt-get update && \
    apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get install -y gcc python3-dev graphviz graphviz-dev

# Install any needed packages specified in requirements.txt
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY ./core_backend/ /usr/src/app

# Copy entrypoint and .env with debugging
COPY ./dockerfiles/dev/django/entrypoint-script /usr/src/app/entrypoint-script
COPY ./envs/dev/django/.env /usr/src/app/.env

# Install netcat-openbsd and bash
RUN apt-get update && \
    apt-get install -y netcat-openbsd bash && \
    rm -rf /var/lib/apt/lists/* 
    
RUN export LANG=C.UTF-8
RUN export LANGUAGE=C.UTF-8
RUN export LC_ALL=C.UTF-8

# Expose port 8000
EXPOSE 8000

