services:
  arg_aut_backend:
    build:
      context: .
      dockerfile: dockerfiles/dev/django/dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core_backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./envs/dev/django/.env
    depends_on:
      - db_dev
      - redis_dev

  db_dev:
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=fa_IR.UTF-8"

  redis_dev:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
  redis_data_dev: