/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import { H5 } from "@/components";
import Head from "next/head";
import { useState } from "react";
import AdminAccounting from "@/containers/AdminAccounting/AdminAccounting";
import { useSelector } from "react-redux";
import {useRouter}  from "next/router";
import { useEffect } from "react";
import { notifyEngine } from "@/utils/notifyEngine";

const SuperAdminDashboard = () => {
  const [activeSection, setActiveSection] = useState("accounting");
  const router = useRouter();
  const auth = useSelector((state) => state.auth);
  const [loginStatus, setLoginStatus] = useState(auth.logged);


  const handleButtonClick = (section) => {
    setActiveSection(section);
  };
  
  useEffect(() => {
    setLoginStatus(auth.logged);
    if (!loginStatus) {
      notifyEngine("شما باید وارد حساب کاربری خود شوید", "error");
      router.push('/');
    } else {;
    }
  }, [loginStatus, auth.logged, router]);


  const adminMainDashboard = css`
    width: 100%;
    min-height: 100vh;
    background-color: rgb(4, 0, 58);
    display: flex;
    justify-content: space-evenly;
    flex-direction: row;
    align-items: center;
    color: white;
  `;

  const leftSideDashboard = css`
    width: 80%;
    height: 85vh;
    border-right: 1px solid rgb(133, 133, 133);
  `;

  const rightSideDashboard = css`
    width: 20%;
    height: 85vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-evenly;
  `;

  const btnDiv = (isActive) => css`
    width: 80%;
    height: 4%;
    margin: 1rem 0;
    ${isActive
      ? "border-bottom: 1px solid white; background-color: white; border-bottom: 1px solid rgb(90, 2, 2); border-radius: 5rem; color: rgb(4, 0, 58);"
      : "border-bottom: 0px solid white;"}
    border: 0px solid white;
    text-align: center;
    display: flex;
    justify-content: center;
    cursor: pointer;
    background-color: transparent;
    color:white;
    &:hover {
      border-bottom: 1px solid rgb(90, 2, 2);
      background-color: white;
      color: rgb(4, 0, 58);
      border-radius: 5rem;
    }
  `;

  return (
    <>
      <Head>
        <title>داشبورد سوپر ادمین</title>
        <meta name="description" content="Generated by Ali Mahmoodi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_white-150x150.png" />
      </Head>
      <div css={adminMainDashboard}>
        <div css={leftSideDashboard}>
          {activeSection === "accounting" && <AdminAccounting show={true} />}
          {/* دیگر کامپوننت‌ها را اینجا اضافه کنید */}
        </div>
        <div css={rightSideDashboard}>
          <button onClick={() => handleButtonClick("accounting")} css={btnDiv(activeSection === "accounting")}>
            <H5>مدیریت کاربران</H5>
          </button>
          <button onClick={() => handleButtonClick("mailManagement")} css={btnDiv(activeSection === "mailManagement")}>
            <H5>مدیریت بخش نامه ها</H5>
          </button>
          <button onClick={() => handleButtonClick("officeOrganization")} css={btnDiv(activeSection === "officeOrganization")}>
            <H5>مدیریت بخش سازمانی</H5>
          </button>
          <button onClick={() => handleButtonClick("systemConfig")} css={btnDiv(activeSection === "systemConfig")}>
            <H5>مدیریت تنظیمات سیستم</H5>
          </button>
        </div>
      </div>
    </>
  );
};

export default SuperAdminDashboard;