/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { H1,H3 ,BlogPostItem,BlogNewsItem} from "@/components";
import posts from "../../public/SampleData/Blog.json"
import news from "../../public/SampleData/News.json"

const Blog = () => {

    const mainDivBlog = css`
        width:100%;
        height:100vh;
        background-color:rgb(8, 0, 83);
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        color:white;
        position:relative;
        overflow:hidden;
    `
    const headerDivBlog = css`
        width:100%;
        height:fit-content;
        display:flex;
        align-items:center;
        justify-content:center;
        background-image:linear-gradient(to bottom right, rgba(0, 6, 61, 0.48) , rgba(0, 6, 61, 0.48)) ,url(./images/Blog/blog.jpg);
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;
        padding:4rem 0;
        position:absolute;
        top:5%;
        animation: topToDown 1s ease-in;
    `
    const sectionBlogs = css`
        width:60%;
        height:56%;
        position:absolute;
        top:29%;
        left:3%;
        border-radius:10px;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        direction:rtl;
        overflow-y:auto;
        overflow-x:none;
        ::-webkit-scrollbar {
          display: none;
        }
        animation:dropDownAnim 1s ease-in;
    `

    const sectionNews = css`
        width:30%;
        height:23%;
        // box-shadow: 1px 2px 10px 15px rgba(143, 143, 148, 0.4);
        position:absolute;
        top:29%;
        left:67%;
        border-radius:10px;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        direction:rtl;
        overflow-y:auto;
        overflow-x:none;
        padding:1rem 0;
        ::-webkit-scrollbar {
          display: none;
        }
          animation:dropDownAnim 2s ease-in;
    `
    const sectionMovieJournal = css`
        width:30%;
        height:23%;
        // box-shadow: 1px 2px 10px 15px rgba(143, 143, 148, 0.4);
        position:absolute;
        top:59%;
        left:67%;
        border-radius:10px;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        direction:rtl;
        overflow-y:auto;
        overflow-x:none;
        padding:1rem 0;
        ::-webkit-scrollbar {
          display: none;
        }
          animation:dropDownAnim 3s ease-in;
    `

    return(
        <>
        <Head>
          <title>سرزمین من | سفرنامه</title>
          <meta name="description" content="Generated by Ali Mahmoodi" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.ico" />
        </Head>
        <div css={mainDivBlog}>
            <div css={headerDivBlog}>
            <H1>سفرنامه</H1>
            </div>
            <div css={sectionBlogs}>
                {posts.length > 0 ? posts.map((post)=>
                    <BlogPostItem key={`blog-post_${post.id}`} imgUrl={post.imageHeader} postDate={post.date} postWriter={post.writer} postTitle={post.title}/>
                ) :<H1>پستی موجود نیست</H1>}                
            </div>
            <div css={sectionNews}>
                <H3>آخرین اخبار گردشگری</H3>
                {news.length > 0 ? news.map((newsItem)=>(
                    <BlogNewsItem imgUrl={"./images/Blog/blog.jpg"} newsTitle={newsItem.title} newsWriter={newsItem.writer} newsDate={newsItem.date}/>
                )) :<H3>خبری در دسترس نیست !</H3>}
            </div>
            <div css={sectionMovieJournal}>
                <H3>مجله تصویری</H3>
            </div>
        </div>
        </>
        
    )
}

export default Blog