import Head from "next/head";
import IndexSectionOne from "@/containers/IndexSectionOne/IndexSectionOne";

const Home = () => {
  return (
    <>
      <Head>
        <title>اتوماسیون اداری ارگ کریمان</title>
        <meta name="description" ontent="Generated by Ali Mahmoodi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_white-150x150.png" />
      </Head>
      <div>
        <main className="container mx-auto px-4">
            <IndexSectionOne/>  
        </main>
      </div>
    </>
  );
}

export default Home