import Head from "next/head";
import IndexSectionOne from "@/containers/IndexSectionOne/IndexSectionOne";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import { useEffect } from "react";
import { notifyEngine } from "@/utils/notifyEngine";


const Home = () => {
  const router = useRouter()
  const auth = useSelector((state) => state.auth);
  useEffect(() => {
    if (auth.logged) {      
      switch(auth.type){
        case 3:          
          router.push("/SuperAdminDashboard/")
          notifyEngine("شما لاگین هستید", "info");
          break
        case 2:
          router.push("/AdminDashboard")
          notifyEngine("شما لاگین هستید", "info");
          break
        case 1:
          router.push("/UserDashboard")
          notifyEngine("شما لاگین هستید", "info");
          break
      }
       
  }
  }, [auth.logged]); 


  return (
    <>
      <Head>
        <title>اتوماسیون اداری ارگ کریمان</title>
        <meta name="description" ontent="Generated by Ali Mahmoodi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_white-150x150.png" />
      </Head>
      <div>
        <main className="container mx-auto px-4">
            <IndexSectionOne/>  
        </main>
      </div>
    </>
  );
}

export default Home