/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { H1 } from "@/components";
import { useEffect,useState} from "react";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";

const Profile = () => {
    const router = useRouter()
    const auth = useSelector((state)=>(state.auth))
    const [loginStatus, setLoginStatus] = useState(false);
    const mainDivContact = css`
        width:100%;
        height:100vh;
        background-color:rgb(8, 0, 83);
        display:flex;
        align-items:center;
        justify-content:center;
        flex-direction:column;
        color:white;
        postition:relative;
        overflow:hidden;
    `
    const headerDivContact = css`
        width:100%;
        height:fit-content;
        display:flex;
        align-items:center;
        justify-content:center;
        background-image:linear-gradient(to bottom right, rgba(0, 6, 61, 0.48) , rgba(0, 6, 61, 0.48)) ,url(./images/Blog/blog.jpg);
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;
        padding:4rem 0;
        position:absolute;
        top:5%;
        animation: topToDown 1s ease-in;
        `
    
    useEffect(()=>{
        setLoginStatus(Boolean(auth.token && auth.email));
        if(loginStatus){
            switch (auth.type) {
                case 3: router.push("/SuperAdminDashboard"); break;
                case 2: router.push("/AdminDashboard"); break;
                case 1: router.push("/UserDashboard"); break;
                default: router.push("/"); break;
            }
        }
    },[loginStatus])

    return(
        <>
        <Head>
        <title> پروفایل | ارگ کریمان</title>
        <meta name="description" content="Generated by Ali Mahmoodi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_white-150x150.png" />
        </Head>
        <div css={mainDivContact}>
            <div css={headerDivContact}>
                <H1>پروفایل {}</H1>
            </div>
        </div>

        </>
        
    )
}

export default Profile