/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { H5,H1,PrfileInfo,ChangeAvatar,ChangeProfInfo } from "@/components";
import { useEffect,useState} from "react";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";

const Profile = () => {
    const [activeSection, setActiveSection] = useState("profileInfo");
    const router = useRouter()
    const auth = useSelector((state)=>(state.auth))
    const [loginStatus, setLoginStatus] = useState(auth.logged);
    const mainDivContact = css`
        width:100%;
        height:100vh;
        background-color:rgb(8, 0, 83);
        display:flex;
        align-items:center;
        justify-content:center;
        flex-direction:column;
        color:white;
        position:relative;
        overflow:hidden;
    `
    const headerDivContact = css`
        width:100%;
        height:fit-content;
        display:flex;
        align-items:center;
        justify-content:center;
        background-image:linear-gradient(to bottom right, rgba(0, 6, 61, 0.48) , rgba(0, 6, 61, 0.48)) ,url(./images/Blog/blog.jpg);
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;
        padding:4rem 0;
        position:absolute;
        top:5%;
        animation: topToDown 1s ease-in;
        `
    const ProfileBody = css`
        width:100%;
        height:73%;
        position: fixed;
        display:flex;
        align-items:center;
        justify-content:center;
        flex-direction:row;  
        animation: bottomToUp 1s ease-in;
        top:23%;
        background-color: rgba(0, 0, 0, 0.57);

        `

    const rightBody = css`
        width:10%;
        height:90%;
        border-left: 1px solid rgb(133, 133, 133);
        display: flex;
        align-items: center;
        justify-content: space-evenly;
        flex-direction: column;

    `
    const leftBody = css`
        width:90%;
        height:90%;
    `

    useEffect(()=>{
        setLoginStatus(auth.logged);
        if(!loginStatus){
            switch (auth.type) {
                case 3: router.push("/SuperAdminDashboard"); break;
                case 2: router.push("/AdminDashboard"); break;
                case 1: router.push("/UserDashboard"); break;
                default: router.push("/"); break;
            }
        }
    },[loginStatus])

    const handleButtonClick = (section) => {  setActiveSection(section);};

    const btnDiv = (isActive) => css`
      width: 80%;
      height: fit-content;
      margin: 1rem 0;
      ${isActive
        ? "border-bottom: 1px solid white; background-color: white; border-bottom: 1px solid rgb(90, 2, 2); border-radius: 5rem; color: rgb(4, 0, 58);"
        : "border-bottom: 0px solid white;"}
      border: 0px solid white;
      text-align: center;
      display: flex;
      justify-content: center;
      cursor: pointer;
      background-color: transparent;
      color:white;
      &:hover {
        border-bottom: 1px solid rgb(90, 2, 2);
        background-color: white;
        color: rgb(4, 0, 58);
        border-radius: 5rem;
      }
    `;

    return(
        <>
        <Head>
        <title> پروفایل | ارگ کریمان</title>
        <meta name="description" content="Generated by Ali Mahmoodi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_white-150x150.png" />
        </Head>
        <div css={mainDivContact}>
            <div css={headerDivContact}>
               <H1>پروفایل کاربری</H1>
            </div>
            <div css={ProfileBody}>
                <div css={leftBody}>
                    {activeSection === "profileInfo" && <PrfileInfo show={true} />}
                    {activeSection === "avatarEdit" && <ChangeAvatar show={true} />}
                    {activeSection === "profileInfoUpdate" && <ChangeProfInfo show={true} />}
                </div>
                <div css={rightBody}>
                    <button onClick={() => handleButtonClick("profileInfo")} css={btnDiv(activeSection === "profileInfo")}>
                      <H5>اطلاعات کاربری</H5>
                    </button>
                    <button onClick={() => handleButtonClick("profileInfoUpdate")} css={btnDiv(activeSection === "profileInfoUpdate")}>
                      <H5>بروزرسانی اطلاعات کاربری</H5>
                    </button>
                    <button onClick={() => handleButtonClick("avatarEdit")} css={btnDiv(activeSection === "avatarEdit")}>
                      <H5>بروزرسانی آواتار</H5>
                    </button>
                    <button onClick={() => handleButtonClick("changePassword")} css={btnDiv(activeSection === "changePassword")}>
                      <H5>تغییر رمز عبور</H5>
                    </button>
                    <button onClick={() => handleButtonClick("changeEmail")} css={btnDiv(activeSection === "changeEmail")}>
                      <H5>تغییر ایمیل</H5>
                    </button>
                     <button onClick={() => handleButtonClick("changeMobile")} css={btnDiv(activeSection === "changeMobile")}>
                      <H5>تغییر شماره موبایل</H5>
                    </button>
                </div>
            </div>
        </div>

        </>
        
    )
}

export default Profile