/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { H1,Paragraph,Inputs,Button } from "@/components";
import { useState,useEffect } from "react";
import Link from "next/link";
import { useDispatch,useSelector } from "react-redux";
import { LOGIN_ACTION } from "@/actions/auth";
import { useRouter } from "next/router";
import { getMobile ,getToken} from "@/utils/auth";
import { notifyEngine } from "@/utils/notifyEngine";


const Profile = () => {
    const router = useRouter()
    const auth = useSelector((state)=>(state.auth))
    const mobileNumber = getMobile()
    const mainDivContact = css`
        width:100%;
        height:100vh;
        background-color:rgb(8, 0, 83);
        display:flex;
        align-items:center;
        justify-content:center;
        flex-direction:column;
        color:white;
        postition:relative;
        overflow:hidden;
    `
    const headerDivContact = css`
        width:100%;
        height:fit-content;
        display:flex;
        align-items:center;
        justify-content:center;
        background-image:linear-gradient(to bottom right, rgba(0, 6, 61, 0.48) , rgba(0, 6, 61, 0.48)) ,url(./images/Blog/blog.jpg);
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;
        padding:4rem 0;
        position:absolute;
        top:5%;
        animation: topToDown 1s ease-in;
        `
    
    useEffect(()=>{
        const loginStatus = getToken()
        if (!loginStatus){
            router.push("/login")
            notifyEngine("برای ورود به پروفایل باید لاگین شوید","warning")
        }
    },[])

    return(
        <>
        <Head>
          <title>سرزمین من | پروفایل کاربری</title>
          <meta name="description" content="Generated by Ali Mahmoodi" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.ico" />
        </Head>
        <div css={mainDivContact}>
            <div css={headerDivContact}>
                <H1>پروفایل {mobileNumber}</H1>
            </div>
        </div>

        </>
        
    )
}

export default Profile