/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import Head from "next/head";
import { H1,H3,H5 } from "@/components";
import { useEffect, useRef } from "react";


const Login = () => {
    const textAreaRef = useRef(null)
    const logoAreaRef = useRef(null)
    const descAreaRef = useRef(null)

    useEffect(()=>{
        if(descAreaRef !== null){
            logoAreaRef.current.style.display = "flex";
            textAreaRef.current.style.display = "flex";
        }
    },[descAreaRef])

    const mainDivAbout = css`
        width:100%;
        height:100vh;
        background-color:rgb(8, 0, 83);
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        color:white;
        postition:relative;
        overflow:hidden;
    `
    const headerDivAbout = css`
        width:100%;
        height:fit-content;
        display:flex;
        align-items:center;
        justify-content:center;
        background-image:linear-gradient(to bottom right, rgba(0, 6, 61, 0.48) , rgba(0, 6, 61, 0.48)) ,url(./images/Blog/blog.jpg);
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;
        padding:4rem 0;
        position:absolute;
        top:5%;
        animation: topToDown 1s ease-in;

    `

    const descriptionAbout = css`
        width:95%;
        height:60%;
        display:flex;
        align-items:right;
        justify-content: flex-end;
        flex-direction:row;
        position:absolute;
        top:27%;
        border-radius:15px;
        background-image:linear-gradient(to left,rgb(8, 0, 83) 38%, rgba(0, 6, 61, 0.48) ),url(./images/about/abus.jpg);
        background-size:cover;
        background-position:right;
        background-repeat:no-repeat;
        direction:rtl;
        animation: dropDownAnim 2s ease-in;
    `
    const textArea = css`
        width:50%;
        height:100%;
        color:white;
        direction:rtl;
        padding-right:2rem;
        display:none;
        align-items:center;
        justify-content:space-between;
        flex-direction:column;
        text-align:right;
    `
    const iconArea = css`
        width:50%;
        height:100%;
        color:white;
        direction:rtl;
        padding-right:2rem;
        display:none;
        align-items:center;
        justify-content:center;
        flex-direction:column;
    `

    return(
        <>
        <Head>
          <title>سرزمین من | ورود</title>
          <meta name="description" content="Generated by Ali Mahmoodi" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.ico" />
        </Head>
        <div css={mainDivAbout}>
            <div css={headerDivAbout}>
                <H1>ورود</H1>
            </div>
            <div ref={descAreaRef} css={descriptionAbout}>
                <div ref={textAreaRef} css={textArea}>
                    <H3>سرزمین من</H3>
                    <H5>مجموعه سرزمین من با هدف هموار سازی مسیر گردشگری با محوریت حمایت از بوم گردی توسعه پیدا کرده است </H5> 
                    <H5>و سعی شده که پلتفرمی ساده و روان برای صاحبان بوگردی جهت ارایه سرویس به کاربران و دیده شدن صنعت نوپایشان باشد</H5>
                    <H5>در کنار آن سرویسهای همیشگی گردشگری نظیر تور بلیط هتل  نیز ارایه می دهد ولی باز هم پیشنهاد ما تجربه بومگردی با سرزمین من است</H5>
                    <H5>تیمی متشکل از متخصصان گردشگری فناوری بازار کس ب و کارهای استارتاپی گرد هم آمدند تا گردشگری را برای همه آسان و در دسترس قرار بدهند به همراه تجربه ای نو از سرگرمی و خاطرات بیادماندنی</H5>
                </div>
                <div ref={logoAreaRef} css={iconArea}>
                    <img src="./images/logoLight.png" css={css`scale:1.5;`}/>
                </div>
            </div>
        </div>
        </>
        
    )
}

export default Login