# Generated by Django 5.2.1 on 2025-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signitures',
            field=models.ImageField(default='img/mockups/default_man.png', upload_to='signiturs/'),
        ),
    ]
