# Generated by Django 5.2.1 on 2025-05-30 16:29

import accounting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tempcodeauthenticating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/mockups/default_man.png', upload_to=accounting.models.avatar_media_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signitures',
            field=models.ImageField(default='img/mockups/default_man.png', upload_to=accounting.models.signuture_media_path),
        ),
        migrations.CreateModel(
            name='UserLoginDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('browser', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
