# Generated by Django 5.2.1 on 2025-06-01 07:43

import accounting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[accounting.validators.validate_iranian_cellphone_number]),
        ),
    ]
