const actionTypse = {
    // //PRODUCT LIST TYPES
    // GET_LIST_PRODUCTS_STARTED:"GET_LIST_PRODUCTS_STARTED",
    // GET_LIST_PRODUCTS_SUCCESS:"GET_LIST_PRODUCTS_SUCCESS",
    // GET_LIST_PRODUCTS_FAILED: "GET_LIST_PRODUCTS_FAILED",
  
    //GET LOGIN TYPES
    LOGIN_STARTED:"LOGIN_STARTED",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",

    //GET LOGIN TYPES
    LOGOUT_STARTED:"LOGOUT_STARTED",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILED:"LOGOUT_FAILED",

    //GET REGISTER TYPES
    REGISTER_STARTED:"REGISTER_STARTED",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAILED:"REGISTER_FAILED",

    //GET VERIFICATION CODE
    VERIFICATION_STARTED:"VERIFICATION_STARTED",
    VERIFICATION_SUCCESS:"VERIFICATION_SUCCESS",
    VERIFICATION_FAILED:"VERIFICATION_FAILED",

    //GET RETRY VERIFICATION CODE
    RETRY_VERIFICATION_STARTED:"RETRY_VERIFICATION_STARTED",
    RETRY_VERIFICATION_SUCCESS:"RETRY_VERIFICATION_SUCCESS",
    RETRY_VERIFICATION_FAILED:"RETRY_VERIFICATION_FAILED",

    //GET RESET PASSWORD CODE
    RESET_PASSWORD_CODE_STARTED:"RESET_PASSWORD_CODE_STARTED",
    RESET_PASSWORD_CODE_SUCCESS:"RESET_PASSWORD_CODE_SUCCESS",
    RESET_PASSWORD_CODE_FAILED:"RESET_PASSWORD_CODE_FAILED",

    //GET RESET PASSWORD
    RESET_PASSWORD_STARTED:"RESET_PASSWORD_STARTED",
    RESET_PASSWORD_SUCCESS:"RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILED:"RESET_PASSWORD_FAILED",

    // GET PROFILE TYPES
    PROFILE_STARTED:"LOGIN_STARTED",
    PROFILE_SUCCESS:"LOGIN_SUCCESS",
    PROFILE_FAILED: "LOGIN_FAILED",
  
    // VERIFY ME TYPES
    // VERIFY_ME_STARTED:"VERIFY_ME_STARTED",
    // VERIFY_ME_SUCCESS:"VERIFY_ME_SUCCESS",
    // VERIFY_ME_FAILED: "VERIFY_ME_FAILED",
  
    // CART LIST TYPES
    // SET_CART:"SET_CART",
    // ADD_TO_CART:"ADD_TO_CART",
    // REMOVE_FROM_CART:"REMOVE_FROM_CART",
  
    // ALERT TYPES
    // SET_ALERT:"SET_ALERT",
    // PROMOTE_ALERT:"PROMOTE_ALERT",
  
    // LOGOUT ACTION
    // LOGOUT:"LOGOUT",
  
  }
  
  export default actionTypse