# Generated by Django 5.2.1 on 2025-06-01 11:08

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='لوگو شرکت')),
                ('letterhead_a4', models.FileField(blank=True, null=True, upload_to='company/letterheads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='سربرگ A4')),
                ('letterhead_sh5', models.FileField(blank=True, null=True, upload_to='company/letterheads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='سربرگ ش5')),
                ('national_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'شناسه ملی باید ۱۱ رقم باشد.')], verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'کد اقتصادی باید ۱۲ رقم باشد.')], verbose_name='کد اقتصادی')),
                ('establishment_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأسیس')),
            ],
        ),
    ]
