# Generated by Django 5.2.1 on 2025-06-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeorganization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان واحد')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'اولویت 1'), (2, 'اولویت 2'), (3, 'اولویت 3'), (4, 'اولویت 4'), (5, 'اولویت 5'), (6, 'اولویت 6'), (7, 'اولویت 7'), (8, 'اولویت 8'), (9, 'اولویت 9'), (10, 'اولویت 10')], help_text='۱ = بالاترین ارجحیت، ۱۰ = کمترین', unique=True, verbose_name='سطح ارجحیت')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='officeorganization.company', verbose_name='شرکت')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeorganization.departmenttype', verbose_name='نوع واحد')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officeorganization.priority', verbose_name='اولویت سازمانی')),
            ],
        ),
    ]
