# Generated by Django 5.2.1 on 2025-06-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeorganization', '0002_departmenttype_priority_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان سمت')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='officeorganization.department', verbose_name='دپارتمان')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officeorganization.priority', verbose_name='اولویت سمت')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeorganization.positiontype', verbose_name='نوع سمت')),
            ],
            options={
                'unique_together': {('department', 'position_type')},
            },
        ),
    ]
