# Generated by Django 5.2.1 on 2025-06-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_profile_phone_number'),
        ('officeorganization', '0003_positiontype_departmentposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاریخ اختصاص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('department_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='officeorganization.departmentposition', verbose_name='سمت در دپارتمان')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounting.profile', verbose_name='پروفایل')),
            ],
            options={
                'unique_together': {('profile', 'department_position')},
            },
        ),
    ]
