# Generated by Django 5.2.1 on 2025-06-01 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_profile_date_of_birth'),
        ('officeorganization', '0004_profileposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام محل (اختیاری)')),
                ('country', models.CharField(default='ایران', max_length=100, verbose_name='کشور')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی')),
                ('location_type', models.CharField(choices=[('headquarter', 'ستاد مرکزی'), ('branch', 'شعبه'), ('warehouse', 'انبار'), ('factory', 'کارخانه'), ('office', 'دفتر')], max_length=20, verbose_name='نوع محل')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با ۰ شروع شده و ۱۱ رقم باشد.', regex='^0\\d{10}$')], verbose_name='شماره تلفن')),
                ('fax_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با ۰ شروع شده و ۱۱ رقم باشد.', regex='^0\\d{10}$')], verbose_name='شماره فکس')),
                ('members', models.ManyToManyField(blank=True, related_name='locations', to='accounting.profile', verbose_name='پروفایل\u200cهای مرتبط')),
            ],
        ),
    ]
