# Generated by Django 5.2.1 on 2025-06-01 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeorganization', '0005_companylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='economic_code',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'کد اقتصادی باید ۱۲ رقم باشد.')], verbose_name='کد اقتصادی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام شرکت'),
        ),
    ]
